### ISSUE TITLE
problem with lang strings from plugin.xml

### ISSUE THREAD

**Issue by Jimmi08** [Jimmi08/links_page#30]
![image](https://cloud.githubusercontent.com/assets/5429548/18710247/82a95256-8004-11e6-8001-eb7f8808ff09.png)

This is maybe caused by this change.  
https://github.com/Jimmi08/links_page/commit/797fabbde34eebb03ec0d3e0fce7585f3370bd36
or maybe not.

**Comment by yesszus** [comment]
Fixed!
https://github.com/Jimmi08/links_page/pull/31

**Comment by Jimmi08** [comment]
Great. So lang string need to be in  lan attribute in plugin.xml,  Thanks.
