### ISSUE TITLE
Update error....

### ISSUE THREAD

**Issue by rica-carv** [Jimmi08/links_page#33]
Just trying to update the old v1.4 plugin to the new v2.x here, and got this error:
`Fatal error: Call to a member function addError() on a non-object in /home/vhosts/www.-------/e107_plugins/links_page/links.php on line 297`

Any wonder what might be wrong?

**Comment by Jimmi08** [comment]
I\ve updated http://v2demo.e107.sk/links_page/links to latest github and no errors. 

But there is no options to update from 1.0.4 version to this version. Delete all files and replace them with new ones.  Only from version 1.0 (adding self fields) for e107 V2. 
look at links_page_setup.php. and change this:  if($currentVersion == '1.0')

That error means that no e107::message() is set. Don't you have e_meta.php or some other old files there?

**Comment by rica-carv** [comment]
I've donne a complete v1.4 folder delete, and replaced with the V2 from github here, so i was hoping it would work, but is seems not....
