### ISSUE TITLE
Shortcodes only rendered in V2 themes?

### ISSUE THREAD

**Issue by rica-carv** [Jimmi08/links_page#36]
As commented by me [here](https://github.com/e107inc/e107/issues/1597#issuecomment-255736196), as far i've tested it might be a template issue, since old V1.x plugins had custom templates on other location, and v2.x now has them on a templates folder.
It might be that issue, but since the plugin is to run on V2.x or above, i think it's redundant....
V1.x themes should be upgraded or adapted to work with v2.x plugins, right?

**Comment by Jimmi08** [comment]
Yes, they should be updated, but if you moved theme templates to new locations (if it's different, I don't remember) it should work.  With that error I would suppose wrong open php tag or problem with parsing generally. Something in old theme breaks parsing if old plugins are used. You have problem with other plugin, so there will be something in theme. 
Did you use Jayya theme without changes?

**Comment by rica-carv** [comment]
Yes, i did use the old Jayya theme without any changes.
Furthermore testing, i found out that any bootstrap theme renders the page with the shortcodes correctly...

**Comment by Jimmi08** [comment]
You need to insert images new way, there is no update, because I don't know how to do it.

By the way, no problems with yayya theme:
![image](https://cloud.githubusercontent.com/assets/5429548/19656043/8ca5ac30-9a1e-11e6-8c16-99096e607aee.png)

and with adding boostrap files:
![image](https://cloud.githubusercontent.com/assets/5429548/19656064/ac5f9f18-9a1e-11e6-8ddc-ee1ccf390772.png)

**Comment by Jimmi08** [comment]
About my update issues:
http://e107help.org/2771/how-to-upgrade-old-plugins-with-data-in-old-version

**Comment by rica-carv** [comment]
The Jayya error was with the old core plugin, not yours.....

**Comment by rica-carv** [comment]
Regarding update, i've donne it the hard way: Still with the old plugin installed, i deleted it's folder (old v1.4 `links_page`), replaced it with the new plugin (yours `links_page`), and in the admin plugin management area it appeared to update, wich i did so, et voilá, almost all is well (except images, of course...)
