### ISSUE TITLE
Remove usage of "Libraries API" plugin (libraries)

### ISSUE THREAD

**Issue by lonalore** [Jimmi08/links_page#7]
Well, in the last days, my "Libraries API" plugin was integrated into the core, so please use "e_library.php" instead of "e_libraries.php". You can see an example in "e107_plugin/_blank" plugin.

Furthermore, you can detect/load a library with the following methods:
```php
e107::library('detect', 'library_name');
e107::library('load', 'library_name');
```

**Comment by Jimmi08** [comment]
Absolutely great news. I didn't notice this.

**Comment by Jimmi08** [comment]
Hi, just let you know. I realize that I removed other scripts and I needed just media manager on one page. So I restricted using it only for this page and I could avoid to use libraries totally. Thank you very much for your help, it's really nice to hear that this became core feature.

**Comment by lonalore** [comment]
Okay, you're welcome, and thank you! :D
